### ISSUE TITLE
Integrate with latest versions of "TaterTrader" and "Mules and Warehouses"

### ISSUE THREAD

**Issue by MonkWho** [Vectorial1024/v1024_civilian_fleets#10]
TaterTrader is being maintained and updated here - https://github.com/DeadAirRT/TaterTrader
They added even more params the other day and I assume you will need to add them to your mod for things to sync properly.

"Mules and Warehouses" is being maintained and updated here - https://github.com/Misunderstood-Wookiee/Mules-and-Warehouses-Extended
They just had a big version release.

**Comment by Vectorial1024** [comment]
I actually helped out with Misunderstood Wookiee's Mules mod a while ago, and DeadAirRT also notified me of the parameter changes a while ago on EgoSoft Forums too, so I know roughly where the things are at.

Leaving this open until integration is complete.

**Comment by Vectorial1024** [comment]
Implemented as in 957b6baceb45ec07790d55ded3694f3245dfa84a and 3e0aa81c57a5ce327cd2965d5d29f7bf7356c39f . Closing this for now.

You may directly download a copy of this mod from here, or you may wait for the official release some time alter.
