### ISSUE TITLE
Mod availability on Steam

### ISSUE THREAD

**Issue by abouquet** [Vectorial1024/v1024_civilian_fleets#4]
Hi,

Is there a way to make it available on Steam ?

Thanks

**Comment by Vectorial1024** [comment]
Hi, thanks for asking this!

It should be possible to upload this mod to Steam. However, from what I hear, there are some extra steps needed to make this mod also work on Steam, something related to packaging the ui scripts properly. Will have to learn how it works.

So, Steam releases are not immediately available. But they shall be available, just need some time.

I'll leave this open until I release the mod on Steam.

**Comment by Vectorial1024** [comment]
That has been a lot of steps. And it is done: https://steamcommunity.com/sharedfiles/filedetails/?id=2092839403

Now I shall sleep peacefully at night.

**Comment by abouquet** [comment]
Good ! Thanks :)
