### ISSUE TITLE
General Notice: Mules Updated Repo

### ISSUE THREAD

**Issue by Misunderstood-Wookiee** [Vectorial1024/v1024_civilian_fleets#56]
Not to rush anything, this is just a general heads up that a mules update which affects the Compatability of civ fleets resides ready to be published in our dev branch.

We decided it was best to hold off on the main release until you had a chance to update accordingly, I came to understand civ fleets is aware of the pending conflict just making this ticket here as I don't have you on discord etc.

**Comment by Vectorial1024** [comment]
So far I understand this being the `assignSrc` param being added to the rest of the mules.

CivFleet is ready for this, and has released an update just now. But still, as a token of thanks for the delayed deployment on your side, the aforementioned update is conservative in how params are copied for the mules: basically the new code targets only the new version of mules. If `assignSrc` exists then I also set it to `false`, but if it doesnt exist then I just skip it.

This should make it a seamless deployment overall.

Thanks again!

**Comment by Misunderstood-Wookiee** [comment]
Awesome 👍 and you're welcome.
