### ISSUE TITLE
Draft work for X4 v5.0

### ISSUE THREAD

**Issue by Vectorial1024** [Vectorial1024/v1024_civilian_fleets#59]
What are the stuff that we should pay attention to now that X4 5.0 came out?

https://store.steampowered.com/news/app/392160?emclan=103582791460032630&emgid=3138450510784249840

- Scrap recycling (S/M scrap directly transfers to station; low prio)
- Local AutoTrade
- Distribute Wares -> Full Storage

**Comment by MortisLegati** [comment]
From what I've seen, Local AutoTrade is an AutoTrade that just works in-system, like previous X games' not-universe-trader.

**Comment by Vectorial1024** [comment]
Indeed, but eventually, I still need to open up the source code and see for myself what exactly is this Local AutoTrade. The end users want the usable behavior, but I want the definition.

**Comment by Vectorial1024** [comment]
I went through the code definitions, and it would seem that the entire mod has yet again been jammed by EgoSoft:

- No more old AutoTrade (`order.trade.routine`):
  - It has become internal
  - We have replacements Local AutoTrade, Advanced AutoTrade, and Expert AutoTrade
- New default behavior AutoSalvage (`order.salvage.routine`)
  - It seems that it does not restrict salvagers to only work for stations; in principle, free ships can do AutoSalvage by themselves, so we may need to do it
- "Mining does not work" #58 but seems there was no obvious code change

Will need to follow up with a game launch later to see what is and is not.

**Comment by Vectorial1024** [comment]
We don't actually have Export AutoTrade (awkward), but we do have Local AutoTrade and Advanced AutoTrade.

Fortunately the AutoTrade portion seems to be relatively untouched, so we will have better compatibility on that side.

---

Mining fleets failed this time because the range parameter have become internal, which means I cannot pass into it trivially.

This will mean that, unfortunately, mods such as Sanity Sector Mining (relies on this mod) will need to rewrite their compat code.

Looking back, X4 v3.0 (non-miners cannot get Miner assignment), v4.0 (Mimic/Assist) and v5.0 (internal code restriction) all broke mining fleets...

**Comment by Vectorial1024** [comment]
A quick hack was used to fix the miner's compat problem.

It was later decided that we will also do salvager fleets.
