### ISSUE TITLE
Rewrite mod using SirNuke's API

### ISSUE THREAD

**Issue by Vectorial1024** [Vectorial1024/v1024_civilian_fleets#9]
Link:

https://steamcommunity.com/sharedfiles/filedetails/?id=2042901274

This mod is said to provide Steam support to UI mods, something that is previously impossible (or at least difficult to achieve). This should make this mod more stable in everybody's machine, including Win7 (which some users complained about not working).

This can be considered together with #4 and #7.

**Comment by Vectorial1024** [comment]
The extensions options part (#7 ) is complete. However, the right click part is still not ready yet; I want to wait for SirNukes side to be stable before I transition fully onto their side.

**Comment by Vectorial1024** [comment]
A breakthrough.

The success of Just Another Modified UI (https://www.nexusmods.com/x4foundations/mods/450) (JAMUI) hinted the possibility of modifying the UI with only the SirNukes Mod Support API without the use of the Right Click API.

So, to conclude, the Interact Menu API provides a simple and stable way of adding simple right click behaviors, while the Lua Loader API, together with a few "standard" code, provides a simple and much more sturdier way of adding more complicated right click behaviors. The mindset that "SirNukes will include more complex features to the Interact Menu API" may not necessarily be appropriate.

This fills the second part of the SirNukes' conversion plan. Initial tests suggest that the conversion is working as intended.

**Comment by FormBurden** [comment]
Ah sweet, that's good to hear. I've came across this mod before. Never used it, but now I need to since I have SO many fleets.
